apiVersion: v1
kind: Service
metadata:
  name: random-generator-green
  namespace: green-deployment
spec:
  selector:
    app: random-generator
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80       
