apiVersion: v1
kind: Service
metadata:
  name: random-generator-blue
  namespace: blue-deployment
spec:
  selector:
    app: random-generator
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80            
